services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ashu01 
      POSTGRES_PASSWORD: zenashu1520@
      POSTGRES_DB: social_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ashu1520@gmail.com
      PGADMIN_DEFAULT_PASSWORD: zenashu1520@
    ports:
      - '8080:80'
    restart: unless-stopped

  backend:
    build: ./
    ports:
      - '3001:3001'
    volumes:
      - ./:/app
    depends_on:
      - postgres

volumes:
  postgres_data:

# networks:
#   default:
#     external:
#       name: shared-network